name: 新機能 / 新要素の提案
description: 新機能の提案または新要素の提案。一つのIssueにつき一つでお願いします
body:
  - type: input
    id: title
    attributes:
      label: タイトル
    validations:
      required: true

  - type: textarea
    id: contents
    attributes:
      label: 内容
    validations:
      required: true


