name: Java CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set artifact name
        id: artifact_names
        run: |
          ModName=$(awk -F '=' '/mod_name/ { print $2; }' gradle.properties)
          MCVersion=$(awk -F '=' '/minecraft_version/ { print $2; }' gradle.properties)
          ModVersion=$(awk -F '=' '/mod_version/ { print $2; }' gradle.properties)

          echo "forge=build/libs/${ModName}-${MCVersion}-${ModVersion}.jar" >> "$GITHUB_OUTPUT"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@ec92e829475ac0c2315ea8f9eced72db85bb337a # v3.0.0

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive Forge artifact
        uses: actions/upload-artifact@v3
        with:
          name: Forge
          path: |
            ${{ steps.artifact_names.outputs.forge }}
            ${{ steps.artifact_names.outputs.forge }}.asc
